### ISSUE TITLE
VerboseUnparsedAtomHandler: Bug related to get_match_dictionary

### ISSUE THREAD

**Issue by hoeldg** [ait-aecid/logdata-anomaly-miner#1000]
Following error message appears when using the VerboseUnparsedAtomHandler:
```
Traceback (most recent call last):
  File "/usr/bin/aminer", line 755, in <module>
    main()
  File "/usr/bin/aminer", line 480, in main
    run_analysis_child(aminer_config, program_name)
  File "/usr/bin/aminer", line 89, in run_analysis_child
    child_return_status = child.run_analysis(3)
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 334, in run_analysis
    handle_result = fd_handler_object.handle_stream()
  File "/usr/lib/logdata-anomaly-miner/aminer/input/LogStream.py", line 325, in handle_stream
    self.last_consume_state = self.stream_atomizer.consume_data(self.log_data_resource.buffer, False)
  File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 164, in consume_data
    if self.dispatch_atom(log_atom):
  File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 184, in dispatch_atom
    if handler.receive_atom(log_atom):
  File "/usr/lib/logdata-anomaly-miner/aminer/analysis/AtomFilters.py", line 52, in receive_atom
    handler_result = handler.receive_atom(log_atom)
  File "/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathDetector.py", line 64, in receive_atom
    for path in log_atom.parser_match.get_match_dictionary().keys():
AttributeError: 'NoneType' object has no attribute 'get_match_dictionary'
sys:1: ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_DGRAM, proto=0>
aminer: Analysis child process 14664 terminated unexpectedly with signal 0x100
```

**Comment by dITySoftware** [comment]
Please add information like the branch used, config and loglines.
This error does not appear to be a bug IN the VerboseUnparsedAtomHandler (but it may be related).

**Comment by hoeldg** [comment]
Minimal example:

Config:
```
Parser:
        - id: a_str0
          type: FixedDataModelElement
          name: 'fields_str0'
          args: 'null'

        - id: timestamp_time0
          type: DateTimeModelElement
          name: 'timestamp_time0'
          date_format: '%Y-%m-%dT%H:%M:%SZ'

        - id: json
          start: True
          type: JsonModelElement
          name: 'model'
          optional_key_prefix: '_'
          key_parser_dict:
            a: a_str0
            timestamp: timestamp_time0


Input:
        # verbose: True
        multi_source: False
        json_format: True
        timestamp_paths:
          - '/model/timestamp_time0'

Analysis:
        - type: 'ParserCount'
          id: PC
          paths:
            - '/model'
          report_interval: 5

        - type: "VerboseUnparsedAtomHandler"
          id: VUAH


EventHandlers:
        - id: "stpe"
          json: true # optional default: false
          type: "StreamPrinterEventHandler"
```

Log:
```
{"a": "a", "timestamp": "2021-12-07T10:00:00Z"}
```

**Comment by hoeldg** [comment]
The error does not appear without the VerboseUnparsedAtomHandler

**Comment by dITySoftware** [comment]
The error happens, because the VerboseUnparsedAtomHandler (also the SimpleUnparsedAtomHandler) must be the first analysis component in the list. This case was missed, because normally the VerboseUnparsedAtomHandler does not need to be defined in the config.

By adding a placeholder entry and replacing it later on, the problem could be fixed.

**Comment by landauermax** [comment]
I think it would be a reasonable solution to add a placeholder and overwrite it in case that the unparsed handler is defined in the config.
