### ISSUE TITLE
New year-Bug: Unit-Test fails

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#1017]
We have the year 2022 now and that might be the problem why the following unit-test fails:

```
FAIL: test3get_match_element_with_different_date_formats (parsing.MultiLocaleDateTimeModelElementTest.MultiLocaleDateTimeModelElementTest)
Test if different date_formats can be used to match data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aminer/aecid-testsuite/unit/parsing/MultiLocaleDateTimeModelElementTest.py", line 142, in test3get_match_element_with_different_date_formats
    self.compare_match_results(data, match_element, match_context, self.id_ + "/format12", self.path, date, 1618326774.201, None)
  File "/home/aminer/aecid-testsuite/unit/TestBase.py", line 150, in compare_match_results
    self.assertEqual(match_element.match_object, match_object)
AssertionError: 1649862774.201 != 1618326774.201
```

**Comment by dITySoftware** [comment]
Please accept the PR #1015 - I have seen and fixed that issue already.
