### ISSUE TITLE
YamlConfig fails in filter_config_errors

### ISSUE THREAD

**Issue by ernstleierzopf** [ait-aecid/logdata-anomaly-miner#1127]
string indices must be integers: https://aecidjenkins.ait.ac.at/job/AECID/job/AECID/job/logdata-anomaly-miner/job/PR-1123/2/console

**Comment by ernstleierzopf** [comment]
Issue seen here: https://aecidjenkins.ait.ac.at/job/AECID/job/AECID/job/logdata-anomaly-miner/job/PR-1187/6/console

**Comment by ernstleierzopf** [comment]
```
Failed to load configuration from /usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
Failed to load configuration from /usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
(<class 'TypeError'>, TypeError('string indices must be integers'), <traceback object at 0x7fa2119607c0>)
Traceback (most recent call last):
  File "/usr/lib/logdata-anomaly-miner/aminer/AminerConfig.py", line 77, in load_config
    aminer_config.load_yaml(yaml_config)
  File "/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py", line 79, in load_yaml
    filter_config_errors(filtered_errors, 'Parser', v.errors, parser_validation_schema)
  File "/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py", line 103, in filter_config_errors
    if 'none or more than one rule validate' in err[key]:
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aminer", line 755, in <module>
    main()
  File "/usr/bin/aminer", line 343, in main
    aminer_config = AminerConfig.load_config(config_file_name)
  File "/usr/lib/logdata-anomaly-miner/aminer/AminerConfig.py", line 87, in load_config
    raise Exception(exception_info[0], exception_info[1], exception_info[2])
Exception: (<class 'TypeError'>, TypeError('string indices must be integers'), <traceback object at 0x7fa2119607c0>)
```

**Comment by ernstleierzopf** [comment]
from MissingMatchPathDetector Wiki test:
```
Starting Postfix Mail Transport Agent: postfix.
aminer: caught signal, shutting down
aminer: caught signal, shutting down
Failed to load configuration from /usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
Failed to load configuration from /usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
(<class 'TypeError'>, TypeError('string indices must be integers'), <traceback object at 0x7fe54d61fd40>)
Traceback (most recent call last):
  File "/usr/lib/logdata-anomaly-miner/aminer/AminerConfig.py", line 77, in load_config
    aminer_config.load_yaml(yaml_config)
  File "/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py", line 79, in load_yaml
    filter_config_errors(filtered_errors, 'Parser', v.errors, parser_validation_schema)
  File "/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py", line 103, in filter_config_errors
    if 'none or more than one rule validate' in err[key]:
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aminer", line 755, in <module>
    main()
  File "/usr/bin/aminer", line 343, in main
    aminer_config = AminerConfig.load_config(config_file_name)
  File "/usr/lib/logdata-anomaly-miner/aminer/AminerConfig.py", line 87, in load_config
    raise Exception(exception_info[0], exception_info[1], exception_info[2])
Exception: (<class 'TypeError'>, TypeError('string indices must be integers'), <traceback object at 0x7fe54d61fd40>)
{"string:['alice']": [1595104087, 5, 1595104141, "string:['/accesslog/combined/combined/user_agent']"], "string:['bob']": [1595104123, 5, 1595104138, "string:['/accesslog/combined/combined/user_agent']"]}

Failed Test in 13.

{"string:['alice']": [1595101398, 5, 0, "string:['/accesslog/combined/combined/user_agent']"]}

```
