### ISSUE TITLE
Problem with passig of parameters with Yml-config

### ISSUE THREAD

**Issue by hoeldg** [ait-aecid/logdata-anomaly-miner#343]
Following problem appears, if a new module is used:

Traceback (most recent call last):
  File "/usr/bin/aminer", line 505, in <module>
    main()
  File "/usr/bin/aminer", line 261, in main
    run_analysis_child(aminer_config, program_name)
  File "/usr/bin/aminer", line 138, in run_analysis_child
    child_return_status = child.run_analysis(3)
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 213, in run_analysis
    self.analysis_context.build_analysis_pipeline()
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 156, in build_analysis_pipeline
    self.aminer_config.build_analysis_pipeline(self)
  File "/usr/lib/logdata-anomaly-miner/aminer/ymlconfig.py", line 704, in build_analysis_pipeline
    auto_include_flag=learn)
TypeError: __init__() got an unexpected keyword argument 'auto_include_flag'
sys:1: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_DGRAM, proto=0>
aminer: Analysis child process 5741 terminated unexpectedly with signal 0x100
sys:1: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=2050, proto=0>

**Comment by hoeldg** [comment]
Error occurred in test module, no changes needed

**Comment by dITySoftware** [comment]
Are you testing on the master branch? ymlconfig.py does not exist any more. Please test on current development branch.
