### ISSUE TITLE
Json Parser throws error when key is not found

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#499]
For example, using the data and config from issue #498, i removed the key _score from one of the input json objects and received the following error. I would expect an anomaly by the UnparsedAtomHandler instead.

Traceback (most recent call last):
  File "/usr/bin/aminer", line 626, in <module>
    main()
  File "/usr/bin/aminer", line 370, in main
    run_analysis_child(aminer_config, program_name)
  File "/usr/bin/aminer", line 81, in run_analysis_child
    child_return_status = child.run_analysis(3)
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 313, in run_analysis
    handle_result = fd_handler_object.handle_stream()
  File "/usr/lib/logdata-anomaly-miner/aminer/input/LogStream.py", line 325, in handle_stream
    self.last_consume_state = self.stream_atomizer.consume_data(self.log_data_resource.buffer, False)
  File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 158, in consume_data
    match_element = self.parsing_model.get_match_element('', match_context)
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py", line 59, in get_match_element
    matches += self.parse_json_dict(self.key_parser_dict, json_match_data, current_path)
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py", line 72, in parse_json_dict
    matches += self.parse_json_dict(value, json_match_data[key], "%s/%s" % (current_path, key))
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py", line 75, in parse_json_dict
    matches += self.parse_json_dict(value[0], json_object, "%s/%s" % (current_path, key))
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py", line 83, in parse_json_dict
    data = json_match_data[split_data[-1]]
KeyError: '_score'
sys:1: ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_DGRAM, proto=0>
aminer: Analysis child process 28923 terminated unexpectedly with signal 0x100

**Comment by landauermax** [comment]
This should also be covered by tests

**Comment by dITySoftware** [comment]
This behavior is intended. It is the same like defining a FixedDataModelElement and then the fixed data does not occur.
For optional keys a parameter called optional_key_prefix is implemented and set to 'optional_key_' by default.

In your case i guess that setting the optional_key_prefix to '_' is the way to go.

I have tested it by removing one _score and it works perfectly.

**Comment by landauermax** [comment]
This should be changed then. If a fixed data does not occur, the FixedDataModelElement will generate an unparsed atom anomaly, but not stop the aminer with an error. The aminer should never just stop running unexpectedly, whatever input data occurs.

**Comment by dITySoftware** [comment]
> This should be changed then. If a fixed data does not occur, the FixedDataModelElement will generate an unparsed atom anomaly, but not stop the aminer with an error. The aminer should never just stop running unexpectedly, whatever input data occurs.

You are right. If the key does not exist, no match is found - in this case the element goes to the VerboseUnparsedAtomHandler.
I have fixed it in PR #502
