### ISSUE TITLE
Analysis Components can not handle some data from the Base64StringModelElement. 

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#540]
```
Traceback (most recent call last):
  File "/usr/bin/aminer", line 625, in <module>
    main()
  File "/usr/bin/aminer", line 369, in main
    run_analysis_child(aminer_config, program_name)
  File "/usr/bin/aminer", line 81, in run_analysis_child
    child_return_status = child.run_analysis(3)
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 313, in run_analysis
    handle_result = fd_handler_object.handle_stream()
  File "/usr/lib/logdata-anomaly-miner/aminer/input/LogStream.py", line 325, in handle_stream
    self.last_consume_state = self.stream_atomizer.consume_data(self.log_data_resource.buffer, False)
  File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 164, in consume_data
    if self.dispatch_atom(log_atom):
  File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 184, in dispatch_atom
    if handler.receive_atom(log_atom):
  File "/usr/lib/logdata-anomaly-miner/aminer/analysis/AtomFilters.py", line 52, in receive_atom
    handler_result = handler.receive_atom(log_atom)
  File "/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathDetector.py", line 88, in receive_atom
    match_value = match_value.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 63: invalid start byte
sys:1: ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_DGRAM, proto=0>
aminer: Analysis child process 150101 terminated unexpectedly with signal 0x100
```

**Comment by dITySoftware** [comment]
```
                    if isinstance(match_value, bytes):
                        if not match_value.isascii():
                            match_value = match_element.match_string
                        match_value = match_value.decode()
```

**Comment by dITySoftware** [comment]
Instead use try/except in a loop to find the "right" encoding and transform it to utf-8
