### ISSUE TITLE
Improve error message when parser model receives incorrect data structure

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#719]
The behavior occurs in the current development implementation. It should be reproducible with following config:

```
LearnMode: True
AminerUser: 'aminer'
AminerGroup: 'aminer'

LogResourceList:
        - 'file:///home/ubuntu/xyz.log'

Parser:
        - id: testmodel
          type: FixedDataModelElement
          name: 'test'
          args: 'test'

        - id: model
          start: True
          type: SequenceModelElement
          name: 'parser'
          args: testmodel

Input:
        verbose: True
        multi_source: False
        timestamp_paths: "/parser/model/type/syscall/time"


Analysis:
        - type: 'ParserCount'
          paths:
            - '/parser/model/type_str'
          report_interval: 5

EventHandlers:
        - id: "stpe"
          json: true
          type: "StreamPrinterEventHandler"
```

The input file does not need to exist. The following error is printed:

```
ubuntu@user-0:~$ sudo aminer -c /etc/aminer/config.yml
WARNING: file or socket '/home/ubuntu/xyz.log' does not exist (yet)!
Traceback (most recent call last):
  File "/usr/bin/aminer", line 751, in <module>
    main()
  File "/usr/bin/aminer", line 476, in main
    run_analysis_child(aminer_config, program_name)
  File "/usr/bin/aminer", line 88, in run_analysis_child
    child_return_status = child.run_analysis(3)
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 234, in run_analysis
    self.analysis_context.build_analysis_pipeline()
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 170, in build_analysis_pipeline
    self.aminer_config.build_analysis_pipeline(self)
  File "/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py", line 129, in build_analysis_pipeline
    parsing_model = build_parsing_model()
  File "/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py", line 240, in build_parsing_model
    parser_model_dict[item['id']] = item['type'].func(item['name'], children)
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/SequenceModelElement.py", line 44, in __init__
    raise TypeError(msg)
TypeError: every child has to be of the type ModelElementInterface.
sys:1: ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_DGRAM, proto=0>
aminer: Analysis child process 17984 terminated unexpectedly with signal 0x100
```

It seems that passing the children to the sequencemodelelement is broken.

**Comment by dITySoftware** [comment]
looks like you made a mistake in configuring the SequenceModelElement. args has to be of type list. Currently it only is FixedDataModelElement instead of [FixedDataModelElement].

**Comment by landauermax** [comment]
Thanks, you are right, this solved the problem.

But I think it would be good to have a better error message for cases where parser elements that expect only values or only lists and are given the opposite, because it is not easy to see what causes the error. Let's leave this issue open for this enhancement.

**Comment by dITySoftware** [comment]
I will fix that soon.
